name: "CI"
on:
  pull_request:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nixos/nix:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        run: |
          nix-shell shell.nix --run "make -C tinywl -f Makefile.shared && cabal build"
